--
-- PostgreSQL database dump
--

-- Dumped from database version 12.22 (Ubuntu 12.22-0ubuntu0.20.04.4)
-- Dumped by pg_dump version 12.22 (Ubuntu 12.22-0ubuntu0.20.04.4)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE universe;
--
-- Name: universe; Type: DATABASE; Schema: -; Owner: freecodecamp
--

CREATE DATABASE universe WITH TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'C.UTF-8' LC_CTYPE = 'C.UTF-8';


ALTER DATABASE universe OWNER TO freecodecamp;

\connect universe

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: galaxy; Type: TABLE; Schema: public; Owner: freecodecamp
--

CREATE TABLE public.galaxy (
    galaxy_id integer NOT NULL,
    name character varying(100) NOT NULL,
    diameter_light_years numeric(12,2),
    spiral_arms_count integer DEFAULT 0,
    has_active_nucleus boolean DEFAULT false,
    description text
);


ALTER TABLE public.galaxy OWNER TO freecodecamp;

--
-- Name: galaxy_galaxy_id_seq; Type: SEQUENCE; Schema: public; Owner: freecodecamp
--

ALTER TABLE public.galaxy ALTER COLUMN galaxy_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.galaxy_galaxy_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: moon; Type: TABLE; Schema: public; Owner: freecodecamp
--

CREATE TABLE public.moon (
    moon_id integer NOT NULL,
    name character varying(100) NOT NULL,
    planet_id integer NOT NULL,
    radius_km numeric(8,1),
    discovery_year integer
);


ALTER TABLE public.moon OWNER TO freecodecamp;

--
-- Name: moon_moon_id_seq; Type: SEQUENCE; Schema: public; Owner: freecodecamp
--

ALTER TABLE public.moon ALTER COLUMN moon_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.moon_moon_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: planet; Type: TABLE; Schema: public; Owner: freecodecamp
--

CREATE TABLE public.planet (
    planet_id integer NOT NULL,
    name character varying(100) NOT NULL,
    star_id integer NOT NULL,
    mass_relative_to_earth numeric(10,4),
    has_rings boolean DEFAULT false
);


ALTER TABLE public.planet OWNER TO freecodecamp;

--
-- Name: planet_planet_id_seq; Type: SEQUENCE; Schema: public; Owner: freecodecamp
--

ALTER TABLE public.planet ALTER COLUMN planet_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.planet_planet_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: space_mission; Type: TABLE; Schema: public; Owner: freecodecamp
--

CREATE TABLE public.space_mission (
    space_mission_id integer NOT NULL,
    name character varying(100) NOT NULL,
    launch_year integer NOT NULL,
    is_manned boolean DEFAULT false
);


ALTER TABLE public.space_mission OWNER TO freecodecamp;

--
-- Name: space_mission_mission_id_seq; Type: SEQUENCE; Schema: public; Owner: freecodecamp
--

ALTER TABLE public.space_mission ALTER COLUMN space_mission_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.space_mission_mission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: star; Type: TABLE; Schema: public; Owner: freecodecamp
--

CREATE TABLE public.star (
    star_id integer NOT NULL,
    name character varying(100) NOT NULL,
    galaxy_id integer NOT NULL,
    surface_temperature_celcius integer,
    spectral_type character varying(10),
    is_luminous boolean DEFAULT true
);


ALTER TABLE public.star OWNER TO freecodecamp;

--
-- Name: star_star_id_seq; Type: SEQUENCE; Schema: public; Owner: freecodecamp
--

ALTER TABLE public.star ALTER COLUMN star_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.star_star_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: galaxy; Type: TABLE DATA; Schema: public; Owner: freecodecamp
--

INSERT INTO public.galaxy VALUES (1, 'Milky Way', 100000.00, 4, false, NULL);
INSERT INTO public.galaxy VALUES (2, 'Andromeda', 220000.00, 2, true, NULL);
INSERT INTO public.galaxy VALUES (3, 'Triangulum', 60000.00, 2, false, NULL);
INSERT INTO public.galaxy VALUES (4, 'Sombrero', 50000.00, 0, true, NULL);
INSERT INTO public.galaxy VALUES (5, 'Whirlpool', 76000.00, 2, true, NULL);
INSERT INTO public.galaxy VALUES (6, 'Large Magellanic Cloud', 14000.00, 1, false, NULL);


--
-- Data for Name: moon; Type: TABLE DATA; Schema: public; Owner: freecodecamp
--

INSERT INTO public.moon VALUES (1, 'Moon', 3, 1737.4, -4000);
INSERT INTO public.moon VALUES (2, 'Phobos', 4, 11.2, 1877);
INSERT INTO public.moon VALUES (3, 'Deimos', 4, 6.2, 1877);
INSERT INTO public.moon VALUES (4, 'Io', 5, 1821.6, 1610);
INSERT INTO public.moon VALUES (5, 'Europa', 5, 1560.8, 1610);
INSERT INTO public.moon VALUES (6, 'Ganymede', 5, 2634.1, 1610);
INSERT INTO public.moon VALUES (7, 'Callisto', 5, 2410.3, 1610);
INSERT INTO public.moon VALUES (8, 'Mimas', 6, 198.2, 1789);
INSERT INTO public.moon VALUES (9, 'Enceladus', 6, 252.1, 1789);
INSERT INTO public.moon VALUES (10, 'Tethys', 6, 531.1, 1684);
INSERT INTO public.moon VALUES (11, 'Dione', 6, 561.4, 1684);
INSERT INTO public.moon VALUES (12, 'Rhea', 6, 763.8, 1672);
INSERT INTO public.moon VALUES (13, 'Titan', 6, 2574.7, 1655);
INSERT INTO public.moon VALUES (14, 'Iapetus', 6, 734.5, 1671);
INSERT INTO public.moon VALUES (15, 'Ariel', 7, 578.9, 1851);
INSERT INTO public.moon VALUES (16, 'Umbriel', 7, 584.7, 1851);
INSERT INTO public.moon VALUES (17, 'Titania', 7, 788.4, 1787);
INSERT INTO public.moon VALUES (18, 'Oberon', 7, 761.4, 1787);
INSERT INTO public.moon VALUES (19, 'Miranda', 7, 235.8, 1948);
INSERT INTO public.moon VALUES (20, 'Triton', 8, 1353.4, 1846);


--
-- Data for Name: planet; Type: TABLE DATA; Schema: public; Owner: freecodecamp
--

INSERT INTO public.planet VALUES (1, 'Mercury', 1, 0.0553, false);
INSERT INTO public.planet VALUES (2, 'Venus', 1, 0.8150, false);
INSERT INTO public.planet VALUES (3, 'Earth', 1, 1.0000, false);
INSERT INTO public.planet VALUES (4, 'Mars', 1, 0.1070, false);
INSERT INTO public.planet VALUES (5, 'Jupiter', 1, 317.8000, true);
INSERT INTO public.planet VALUES (6, 'Saturn', 1, 95.2000, true);
INSERT INTO public.planet VALUES (7, 'Uranus', 1, 14.5000, true);
INSERT INTO public.planet VALUES (8, 'Neptune', 1, 17.1000, true);
INSERT INTO public.planet VALUES (9, 'Sirius Prime', 2, 2.5000, false);
INSERT INTO public.planet VALUES (10, 'Centauri Rock', 3, 0.8500, false);
INSERT INTO public.planet VALUES (11, 'Centauri Gas', 3, 150.0000, true);
INSERT INTO public.planet VALUES (12, 'Sombrero Giant', 4, 500.0000, true);


--
-- Data for Name: space_mission; Type: TABLE DATA; Schema: public; Owner: freecodecamp
--

INSERT INTO public.space_mission OVERRIDING SYSTEM VALUE VALUES (1, 'Apollo 11', 1969, true);
INSERT INTO public.space_mission OVERRIDING SYSTEM VALUE VALUES (2, 'Voyager 1', 1977, false);
INSERT INTO public.space_mission OVERRIDING SYSTEM VALUE VALUES (3, 'Hubble Space Telescope', 1990, false);


--
-- Data for Name: star; Type: TABLE DATA; Schema: public; Owner: freecodecamp
--

INSERT INTO public.star VALUES (1, 'Sun', 1, 5778, NULL, true);
INSERT INTO public.star VALUES (2, 'Sirius', 1, 9940, NULL, true);
INSERT INTO public.star VALUES (3, 'Alpha Centauri A', 1, 5790, NULL, true);
INSERT INTO public.star VALUES (4, 'Andromedae Alpha', 2, 13800, NULL, true);
INSERT INTO public.star VALUES (5, 'Triangulum Prime', 3, 4000, NULL, true);
INSERT INTO public.star VALUES (6, 'Sombrero Major', 4, 12000, NULL, true);


--
-- Name: galaxy_galaxy_id_seq; Type: SEQUENCE SET; Schema: public; Owner: freecodecamp
--

SELECT pg_catalog.setval('public.galaxy_galaxy_id_seq', 6, true);


--
-- Name: moon_moon_id_seq; Type: SEQUENCE SET; Schema: public; Owner: freecodecamp
--

SELECT pg_catalog.setval('public.moon_moon_id_seq', 20, true);


--
-- Name: planet_planet_id_seq; Type: SEQUENCE SET; Schema: public; Owner: freecodecamp
--

SELECT pg_catalog.setval('public.planet_planet_id_seq', 12, true);


--
-- Name: space_mission_mission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: freecodecamp
--

SELECT pg_catalog.setval('public.space_mission_mission_id_seq', 3, true);


--
-- Name: star_star_id_seq; Type: SEQUENCE SET; Schema: public; Owner: freecodecamp
--

SELECT pg_catalog.setval('public.star_star_id_seq', 6, true);


--
-- Name: galaxy galaxy_name_key; Type: CONSTRAINT; Schema: public; Owner: freecodecamp
--

ALTER TABLE ONLY public.galaxy
    ADD CONSTRAINT galaxy_name_key UNIQUE (name);


--
-- Name: galaxy galaxy_pkey; Type: CONSTRAINT; Schema: public; Owner: freecodecamp
--

ALTER TABLE ONLY public.galaxy
    ADD CONSTRAINT galaxy_pkey PRIMARY KEY (galaxy_id);


--
-- Name: moon moon_name_key; Type: CONSTRAINT; Schema: public; Owner: freecodecamp
--

ALTER TABLE ONLY public.moon
    ADD CONSTRAINT moon_name_key UNIQUE (name);


--
-- Name: moon moon_pkey; Type: CONSTRAINT; Schema: public; Owner: freecodecamp
--

ALTER TABLE ONLY public.moon
    ADD CONSTRAINT moon_pkey PRIMARY KEY (moon_id);


--
-- Name: planet planet_name_key; Type: CONSTRAINT; Schema: public; Owner: freecodecamp
--

ALTER TABLE ONLY public.planet
    ADD CONSTRAINT planet_name_key UNIQUE (name);


--
-- Name: planet planet_pkey; Type: CONSTRAINT; Schema: public; Owner: freecodecamp
--

ALTER TABLE ONLY public.planet
    ADD CONSTRAINT planet_pkey PRIMARY KEY (planet_id);


--
-- Name: space_mission space_mission_name_key; Type: CONSTRAINT; Schema: public; Owner: freecodecamp
--

ALTER TABLE ONLY public.space_mission
    ADD CONSTRAINT space_mission_name_key UNIQUE (name);


--
-- Name: space_mission space_mission_pkey; Type: CONSTRAINT; Schema: public; Owner: freecodecamp
--

ALTER TABLE ONLY public.space_mission
    ADD CONSTRAINT space_mission_pkey PRIMARY KEY (space_mission_id);


--
-- Name: star star_name_key; Type: CONSTRAINT; Schema: public; Owner: freecodecamp
--

ALTER TABLE ONLY public.star
    ADD CONSTRAINT star_name_key UNIQUE (name);


--
-- Name: star star_pkey; Type: CONSTRAINT; Schema: public; Owner: freecodecamp
--

ALTER TABLE ONLY public.star
    ADD CONSTRAINT star_pkey PRIMARY KEY (star_id);


--
-- Name: moon moon_planet_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: freecodecamp
--

ALTER TABLE ONLY public.moon
    ADD CONSTRAINT moon_planet_id_fkey FOREIGN KEY (planet_id) REFERENCES public.planet(planet_id);


--
-- Name: planet planet_star_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: freecodecamp
--

ALTER TABLE ONLY public.planet
    ADD CONSTRAINT planet_star_id_fkey FOREIGN KEY (star_id) REFERENCES public.star(star_id);


--
-- Name: star star_galaxy_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: freecodecamp
--

ALTER TABLE ONLY public.star
    ADD CONSTRAINT star_galaxy_id_fkey FOREIGN KEY (galaxy_id) REFERENCES public.galaxy(galaxy_id);


--
-- PostgreSQL database dump complete
--

